#!/usr/bin/env python3
"""Make a channel-stress copy of scenarios/s15_three_layer.json by injecting RANDOM
send_channel commands across all (non-special) nodes, layers, channels, and the active
time window. Deterministic given --seed, so the scenario is reproducible.

The base s15 is engine-neutral (script: dv_dual_sf.lua); this copy stays neutral too —
run it on either engine (Lua channel = pull-based; meshroute channel = the 2026-06-08
flood). Channels are leaf-scoped, so this stresses within-layer flood propagation in
all 3 layers + the bridge (gateway) consumer/provider behaviour.

Usage:  python3 tools/gen_s15_channels.py [--n 120] [--seed 1522] [--channels 0,1,2,3]
                                          [--out scenarios/s15_three_layer_channels.json]
"""
import argparse, json, os, random

BASE = "scenarios/s15_three_layer.json"
# nodes excluded from the random origination pool: `newbie` is the late-joiner (unprovisioned early).
EXCLUDE = {"newbie"}


def pad(label: str, want: int) -> str:
    """label + a deterministic alpha filler to a realistic channel body length (<= ~120 B)."""
    filler = "-the-quick-brown-fox-jumps-over-the-lazy-dog" * 4
    return (label + filler)[:want]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=120, help="random channel messages to inject")
    ap.add_argument("--seed", type=int, default=1522, help="PRNG seed (reproducible)")
    ap.add_argument("--channels", default="0,1,2,3", help="comma-separated channel ids")
    ap.add_argument("--base", default=BASE)
    ap.add_argument("--out", default="scenarios/s15_three_layer_channels.json")
    args = ap.parse_args()

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with open(os.path.join(repo, args.base)) as f:
        d = json.load(f)

    pool = [n["name"] for n in d["nodes"] if n["name"] not in EXCLUDE]
    layer_of = {n["name"]: n["config"].get("layer_id") for n in d["nodes"]}
    channels = [int(c) for c in args.channels.split(",")]

    # Active window: from after discovery (the existing commands start at 600 s) to a margin
    # before the end, snapped to 1 s so the at_ms read cleanly.
    dur = d["simulation"]["duration_ms"]
    lo, hi = 600_000, dur - 100_000

    rng = random.Random(args.seed)
    injected = []
    for seq in range(args.n):
        node = rng.choice(pool)
        ch = rng.choice(channels)
        at = rng.randrange(lo, hi, 1000)
        # label encodes the truth (origin layer + channel + seq) so the analyzer can check
        # leaf-scoping (a L1-origin channel msg must not appear on L2/L3 nodes).
        label = f"L{layer_of[node]}-ch{ch}-{node}-{seq}"
        body = pad(label, rng.randint(20, 110))
        injected.append({"at_ms": at, "node": node, "command": f"send_channel {ch} {body}"})

    # Default this scenario to the C++ port (the channel FLOOD under test). The Lua `script` is kept so
    # `lus --engine lua --allow-deprecated-lua <scenario>` still runs the pull-plane baseline for a
    # differential — the Lua engine is DEPRECATED + UNSUPPORTED (2026-07-25 ruling) and is REFUSED
    # without that opt-in; it survives only as the frozen parity reference.
    for n in d["nodes"]:
        n["engine"] = "meshroute"

    d["commands"] = sorted(d["commands"] + injected, key=lambda c: c["at_ms"])
    d["_name"] = "s15_three_layer_channels"
    d["_desc"] = (f"s15 three-layer topology + {args.n} RANDOM send_channel messages "
                  f"(seed={args.seed}, channels={channels}) injected across all nodes/layers/time, "
                  f"interleaved with the base DM/layer/channel traffic. Channels are leaf-scoped: "
                  f"stresses within-layer flood propagation + bridge (gateway) consumer/provider. "
                  f"Generated by tools/gen_s15_channels.py.")

    with open(os.path.join(repo, args.out), "w") as f:
        json.dump(d, f, indent=2)
    print(f"wrote {args.out}: {len(d['commands'])} commands "
          f"({len(injected)} injected channel msgs on channels {channels} across {len(pool)} nodes)")


if __name__ == "__main__":
    main()
